name = "tpil25"
version = "0.1.0"
keywords = ["math"]
defaultTargets = ["TPIL25"]

[leanOptions]
autoImplicit = false

[[require]]
name = "mathlib"
scope = "leanprover-community"
rev = "v4.15.0"

[[lean_lib]]
name = "TPIL25"
globs = ["TPIL25.+"]
